[workspace]
resolver = "2"
members = [
    "deadpool",
    "diesel",
    "lapin",
    "memcached",
    "postgres",
    "r2d2",
    "redis",
    "runtime",
    "sqlite",
    "sync",
    "examples/*",
]
