[package]
name = "example-redis-actix-web"
version = "0.0.0"
edition = "2018"
resolver = "2"
authors = ["Tomas Hromada <tomas@hey.com>"]
publish = false

[dependencies]
actix-web = "4"
deadpool-redis = { path = "../../redis" }
